name: CI Test for Docker Compose

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql_db:
        image: mysql:latest
        env:
    #       MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
    #       MYSQL_DATABASE: ${{ secrets.DB_NAME }}
          ports:
            - 3306:3306
    #     options: >-
    #       --health-cmd="mysqladmin ping -h localhost -u root -p${{ secrets.DB_PASSWORD }}"
    #       --health-interval=30s
    #       --health-timeout=10s
    #       --health-retries=5

    # steps:
    #   - name: Checkout repository
    #     uses: actions/checkout@v3

    #   - name: Set up Docker Buildx
    #     uses: docker/setup-buildx-action@v2

    #   - name: Log in to GitHub Container Registry
    #     uses: docker/login-action@v2
    #     with:
    #       registry: ghcr.io
    #       username: ${{ github.actor }}
    #       password: ${{ secrets.GITHUB_TOKEN }}

    #   - name: Build and push Docker images
    #     run: |
    #       docker-compose -f docker-compose.yaml build

    #   - name: Run Docker Compose
    #     run: |
    #       docker-compose -f docker-compose.yaml up -d

    #   - name: Run tests
    #     run: |
    #       # Add your test commands here
    #       # docker exec app_container pytest /usr/src/app/tests
    #       run: echo "TODO" 

    #   - name: Tear down Docker Compose
    #     if: always()
    #     run: |
    #       docker-compose -f docker-compose.yaml down -v
